# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'cnodeReactNative' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cnodeReactNative

  target 'cnodeReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
  end

end
